"""Initial migration

Revision ID: 2cf86d906028
Revises:
Create Date: 2026-02-01 16:01:09.695806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cf86d906028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add workout_day column with default value 'A' for existing rows
    # SQLite has limited ALTER TABLE support, so we only add the new column
    # and create the index. Type changes are skipped as they don't affect functionality.

    # Check if workout_day column already exists to handle partial migration
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('exercises')]

    if 'workout_day' not in columns:
        op.add_column('exercises', sa.Column('workout_day', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default='A'))

    # Create index if it doesn't exist
    indexes = [idx['name'] for idx in inspector.get_indexes('exercises')]
    if 'ix_exercises_name' not in indexes:
        op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the changes made in upgrade()
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_column('exercises', 'workout_day')
    # ### end Alembic commands ###
